### ISSUE TITLE
#1601 - OPR (Ciclo de Gente)

### ISSUE THREAD

**Issue by WillianMarquezini** [Welington88/PortalGenteAmbev#100]
***Descrição:***
Incluir filtro no demitidos ano YDT/ mês, filtro setor, total demitidos. Inserir admitidos com filtro ano YDT/ mês, filtro setor, total admitidos. E verificar página 4 underperformers, numero de admitidos menor que 2 anos, não condiz o real.

**Comment by Welington88** [comment]
@WillianMarquezini está homologado ?

**Comment by WillianMarquezini** [comment]
@Welington88 sim
