### ISSUE TITLE
#1317 - Power BI - Tendencia não está atualizando no Damata BI

### ISSUE THREAD

**Issue by WillianMarquezini** [Welington88/PortalGenteAmbev#80]
Tendência não está atualizando no Damata BI, ela fica dentro da Remuneração. 

Fiz em 15/10 e até hoje não atualizou. 

Pode verificar por favor.

**Comment by Welington88** [comment]
@WillianMarquezini foi resolvido com chamado issue #68

**Comment by Welington88** [comment]
@WillianMarquezini pode fechar
