### ISSUE TITLE
#1550 - Bate Papos Integração

### ISSUE THREAD

**Issue by WillianMarquezini** [Welington88/PortalGenteAmbev#89]
**Solicitante:** Priscilla Gomes da Mata

**Descrição:**
Boa tarde Wel! Gostaria de solicitar, que assim que possível, passasse para o BI, nosso controle de Bate Papos Integração. Quando for realizar o chamado, pode me solicitar o que for preciso para facilitar a chamado. At.te.

**Comment by Welington88** [comment]
Solicitar a Arquivo padrão para usuário.

**Comment by Welington88** [comment]
O arquivo ?

**Comment by WillianMarquezini** [comment]
ainda esperando o arquivo
