### ISSUE TITLE
#1556 - BI TurnOver

### ISSUE THREAD

**Issue by WillianMarquezini** [Welington88/PortalGenteAmbev#90]
Solicitante : Priscilla Gomes da Mata

Descrição:
Boa tarde Wel! Recebemos por e-mail a nova base de calculo para nossa meta de TurnOver 2022. Favor inseri-la em nosso BI de TurnOver. Segue anexo memoria de calculo. Obrigada!

**Comment by WillianMarquezini** [comment]
https://damata.quickgestao.com/arquivos/baixar?codigo=6d9e9d&caminho=damata/chamados/principal/1/1645040767620d547f96a84.xlsx

base de calculo para download

**Comment by Welington88** [comment]
Cálculo não mudou nada. Está tudo igual ? O que é para mudar ? Confirma com Time de RH

**Comment by Welington88** [comment]
Então o que mudou ?

**Comment by Welington88** [comment]
@WillianMarquezini está igual ao do egente não mudou nada ?

**Comment by WillianMarquezini** [comment]
ok vou verificar oq mudou
