### ISSUE TITLE
#1611 - POWER BI FINANCEIRO 

### ISSUE THREAD

**Issue by WillianMarquezini** [Welington88/PortalGenteAmbev#97]
URGENTE Solicito as adaptações nos BIs de GIRO VASILHAME E COMODATOS DIGITALIZADOS conforme conversamos hoje via zap, qualquer duvida estou a disposição. Atte, Lídia Teodoro

Anexo:
https://damata.quickgestao.com/arquivos/baixar?codigo=6d9e9d&caminho=damata/chamados/principal/1/1646933249622a350110d4c.xlsx

**Comment by Welington88** [comment]
Novo Cálculo segundo a Ambev
![Cálculo Vasilhame1](https://user-images.githubusercontent.com/51893051/157864574-dbe4f3f2-a499-4a4c-bcdd-09b4734910b7.jpeg)
![Cálculo Vasilhame2](https://user-images.githubusercontent.com/51893051/157864580-b361b732-848f-4257-b8b9-214f0c0e808a.jpeg)
![Cálculo Vasilhame3](https://user-images.githubusercontent.com/51893051/157864583-ea991a09-77ed-4421-a3c1-c86abc2bcbee.jpeg)

**Comment by Welington88** [comment]
@WillianMarquezini avisar usuário para verificar o cálculo.

**Comment by Welington88** [comment]
@WillianMarquezini Medidas que foram incluídas 
<img width="1439" alt="Captura de Tela 2022-03-22 às 13 40 56" src="https://user-images.githubusercontent.com/51893051/159531072-d0b4463f-b3e5-43a0-b962-78da43887103.png">
<img width="1435" alt="Captura de Tela 2022-03-22 às 13 41 09" src="https://user-images.githubusercontent.com/51893051/159531095-d6e5bb01-b307-4e6e-8491-e4f51ae8f02c.png">
<img width="1440" alt="Captura de Tela 2022-03-22 às 13 41 22" src="https://user-images.githubusercontent.com/51893051/159531098-288f19bc-bbf4-4ed6-9244-4a331f5dbd9d.png">
<img width="1439" alt="Captura de Tela 2022-03-22 às 13 41 29" src="https://user-images.githubusercontent.com/51893051/159531100-92c17baa-43ff-49f5-9a0a-6dd7146eee9e.png">

**Comment by Welington88** [comment]
Resultado da Tela
<img width="1440" alt="Captura de Tela 2022-03-22 às 13 41 54" src="https://user-images.githubusercontent.com/51893051/159531226-ab5d89f5-a69a-4e63-af71-3bbbb43f4278.png">
<img width="1440" alt="Captura de Tela 2022-03-22 às 13 42 01" src="https://user-images.githubusercontent.com/51893051/159531252-8ff21670-40b6-48eb-8019-e5c7f54096ba.png">

**Comment by WillianMarquezini** [comment]
100% (antiga) -> 90% (nova)

**Comment by Welington88** [comment]
@WillianMarquezini 
<img width="867" alt="Captura de Tela 2022-03-28 às 01 32 27" src="https://user-images.githubusercontent.com/51893051/160327278-e406c391-57ad-42f3-9ace-66a84ce0a160.png">
